### ISSUE TITLE
fromGeoJson prints data even if verbose arg is false

### ISSUE THREAD

**Issue by jipiloub** [TesteurManiak/map_controller_plus#3]
Hello @TesteurManiak 

Thanks so much for porting this lib to Flutter 3. Much appreciated. Here is a request rather than an issue report.

What about executing this `debugPrint` only if verbose is set to true?
https://github.com/TesteurManiak/map_controller_plus/blob/c59f6bd679ab1394500a5a61df35815c59e5a5a5/lib/src/controller.dart#L314

I'm working on big data. So this print is annoying.

**Comment by TesteurManiak** [comment]
Hi, a `verbose` flag is a good idea, I'll try to implement something as soon as I can. If you need it fast do not hesitate to open a PR I'll gladly review it.

**Comment by jipiloub** [comment]
Hey
I was referring to the function argument, which is not used at this line.
Yesterday, I tried to open a PR but was refused because of access rights. Do you need to do anything on your side?

**Comment by TesteurManiak** [comment]
It might be because you cannot directly push a branch on the main repository, you need to fork the repo then open a pull request to contribute.
