### ISSUE TITLE
Does not run on the Web platform

### ISSUE THREAD

**Issue by jipiloub** [TesteurManiak/map_controller_plus#8]
For my project, I target namely the Web platform. 

Until now, I could modify the code of this repo to get polygons displayed in a `flutter_map` widget on the `macOS` platform. But it does not work on the `chrome` platform.

Any idea where it could come from?

**Comment by jipiloub** [comment]
My only hint is that this repo is based on `geojson` which also does not support the `web` platform.

**Comment by TesteurManiak** [comment]
Yeah, as mentioned on pub.dev the package is not web compatible because of the packages [geopoint](https://pub.dev/packages/geopoint) and [geojson](https://pub.dev/packages/geojson) which are both not compatible with the web platform.

**Comment by TesteurManiak** [comment]
Both of those package haven't got any update for more than a year, a solution I could suggest would be to remove those dependencies (and its associated features) so it can be compatible with the web platform.

**Comment by TesteurManiak** [comment]
I'm closing this issue as it is not planned to remove those dependencies for now, do not hesitate to reopen it if needed.
